include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    avoid_unnecessary_containers: true
    sort_constructors_first: true
    unnecessary_this: true
    require_trailing_commas: true
    avoid_void_async: true
